version: "3.7"

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=issecure
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

